MieiCorsi/Controllers/CorsiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MieiCorsi.Models.Services.Application;
using MieiCorsi.Models.ViewModels;

namespace MieiCorsi.Controllers
{
    public class CorsiController : Controller
    {
        private readonly ICourseService courseService;

        public CorsiController(ICourseService courseService) 
            // In questo modo possiamo  creare l'istanza della classe CourseService senza la "NEW" 
            //: Questo meccanismo viene chiamato la DEPENDENCY INJECTION 
            //(il problema a questo punto è che il "CourseController" non può funzionare al meno  che no ci fornisca un istanza proprio di "CourseService" )
        {                                                    
            this.courseService = courseService;
        }
        public async Task<IActionResult> IndexAsync()
        {
            ViewData["Title"] = "Catalogo dei corsi";
           // var courseService = new CourseService();// Istanza della classe CourseService
            List<CourseViewModel> courses = await courseService.GetCoursesAsync();
           
            //lista di corsi restituita dall'istanza della classe CourseService.
            return View(courses);
        }

        public async Task<IActionResult> DetailsAsync(int id)
        {
           // var courseDetailsService = new CourseService();
            CourseDetailsViewModel courseDetails = await courseService.GetDetailsAsync(id);
            ViewData["Title"] = courseDetails.Title;
            return View(courseDetails);
        }

        //Func<DateTime, bool> CanDrive =
        //    dob => dob.AddYears(18) <= DateTime.Today;

        ////lamda function con una sola istruzione nel corpo della funzione.

        //Func<DateTime, bool> CanDriv = (dob) =>
        // {
        //     bool value = dob.AddYears(18) <= DateTime.Today;
        //     return value;
        // };
        //// lamda function con più istruzioni nel corpo della funzione
    }
}

MieiCorsi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MieiCorsi</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    </environment>

    <environment exclude="Development">
        <script src="https://kit.fontawesome.com/635815fc0c.js" crossorigin="anonymous"></script>
    </environment>
    <link rel="stylesheet" href="~/style.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" ><img src="~/logo.svg" height="50" alt="Logo MyCourse"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Corsi" asp-action="Index">CATALOGO CORSI</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top-0 footer text-muted">
        <div class="container">
            &copy; 2020 - MieiCorsi - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>